<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>10.0.0-rc.0</Version>
    <Description>Module de recherche avancée Kinetix.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kinetix.Search.Models\Kinetix.Search.Models.csproj" />
    <ProjectReference Include="..\Kinetix.Services\Kinetix.Services.csproj" />
  </ItemGroup>
</Project>
