//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinetix.ComponentModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinetix.ComponentModel.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la valeur doit être comprise entre {1} et {2}..
        /// </summary>
        internal static string ConstraintIntervalBornes {
            get {
                return ResourceManager.GetString("ConstraintIntervalBornes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au moins une borne doit être définie..
        /// </summary>
        internal static string ConstraintIntervalError {
            get {
                return ResourceManager.GetString("ConstraintIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doit être renseigné.
        /// </summary>
        internal static string ConstraintNotNull {
            get {
                return ResourceManager.GetString("ConstraintNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date doit être comprise entre le 01/01/1753 et le 31/12/9999..
        /// </summary>
        internal static string DateContraintError {
            get {
                return ResourceManager.GetString("DateContraintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;adresse mail doit être de la forme &apos;personne@exemple.com&apos;..
        /// </summary>
        internal static string ErrorConstraintEmail {
            get {
                return ResourceManager.GetString("ErrorConstraintEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la taille doit être inférieure à {0} caractères..
        /// </summary>
        internal static string ErrorConstraintStringLength {
            get {
                return ResourceManager.GetString("ErrorConstraintStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la taille doit être inférieure à {0} caractères et ne comporter aucun caractère spécial..
        /// </summary>
        internal static string ErrorConstraintStringLengthAlpha {
            get {
                return ResourceManager.GetString("ErrorConstraintStringLengthAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le booléen doit être une valeur &apos;True&apos; ou &apos;False&apos;..
        /// </summary>
        internal static string ErrorFormatBooleen {
            get {
                return ResourceManager.GetString("ErrorFormatBooleen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le code postal (ou code INSEE) doit être un nombre composé de 5 chiffres..
        /// </summary>
        internal static string ErrorFormatCodePostal {
            get {
                return ResourceManager.GetString("ErrorFormatCodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code trimestre doit être de la forme aaaaTt..
        /// </summary>
        internal static string ErrorFormatCodeTrimestre {
            get {
                return ResourceManager.GetString("ErrorFormatCodeTrimestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la date saisie doit être au format &apos;jj/mm/aaaa&apos;..
        /// </summary>
        internal static string ErrorFormatDate {
            get {
                return ResourceManager.GetString("ErrorFormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la date saisie est incorrecte..
        /// </summary>
        internal static string ErrorFormatDateValue {
            get {
                return ResourceManager.GetString("ErrorFormatDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;est pas une valeur valide pour un decimal..
        /// </summary>
        internal static string ErrorFormatDecimal {
            get {
                return ResourceManager.GetString("ErrorFormatDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est pas un entier..
        /// </summary>
        internal static string ErrorFormatEntier {
            get {
                return ResourceManager.GetString("ErrorFormatEntier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est pas un Guid valide..
        /// </summary>
        internal static string ErrorFormatGuid {
            get {
                return ResourceManager.GetString("ErrorFormatGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure doit être comprise entre 00:00 et 23:59.
        /// </summary>
        internal static string ErrorFormatHeure {
            get {
                return ResourceManager.GetString("ErrorFormatHeure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est pas un pourcentage valide..
        /// </summary>
        internal static string ErrorFormatPercentage {
            get {
                return ResourceManager.GetString("ErrorFormatPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le taux saisi doit être un décimal compris entre 0 et 100 avec deux chiffres après la virgule..
        /// </summary>
        internal static string ErrorFormatTaux {
            get {
                return ResourceManager.GetString("ErrorFormatTaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le numéro de téléphone doit comporter 10 chiffres..
        /// </summary>
        internal static string ErrorFormatTelephone {
            get {
                return ResourceManager.GetString("ErrorFormatTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la valeur doit être comprise entre {0} non compris et {1} compris.
        /// </summary>
        internal static string ErrorRangeDecimalLeftOpen {
            get {
                return ResourceManager.GetString("ErrorRangeDecimalLeftOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la valeur doit être comprise entre {0} non compris  et {1} non compris.
        /// </summary>
        internal static string ErrorRangeDecimalOpen {
            get {
                return ResourceManager.GetString("ErrorRangeDecimalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la valeur doit être comprise entre {0} et {1} non compris.
        /// </summary>
        internal static string ErrorRangeDecimalRightOpen {
            get {
                return ResourceManager.GetString("ErrorRangeDecimalRightOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ICustomTypeDescriptor not supported.
        /// </summary>
        internal static string ExceptionICustomTypeDescriptorNotSupported {
            get {
                return ResourceManager.GetString("ExceptionICustomTypeDescriptorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value type {0}, {1} expected for property {2}..
        /// </summary>
        internal static string ExceptionInvalidValueType {
            get {
                return ResourceManager.GetString("ExceptionInvalidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported generic type : {0}..
        /// </summary>
        internal static string ExceptionNotSupportedGeneric {
            get {
                return ResourceManager.GetString("ExceptionNotSupportedGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type : {0}.
        /// </summary>
        internal static string ExceptionTypeDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} non supporté pour la propriété &apos;{1}&apos;. Le type attendu est Int32..
        /// </summary>
        internal static string ExceptionTypeInt32Required {
            get {
                return ResourceManager.GetString("ExceptionTypeInt32Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propriété {0} est en lecture seule, impossible de lui affecter une valeur..
        /// </summary>
        internal static string ReadOnlyProperty {
            get {
                return ResourceManager.GetString("ReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format invalide..
        /// </summary>
        internal static string SiretConstraintError {
            get {
                return ResourceManager.GetString("SiretConstraintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string TextBooleanNo {
            get {
                return ResourceManager.GetString("TextBooleanNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string TextBooleanUndefined {
            get {
                return ResourceManager.GetString("TextBooleanUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string TextBooleanYes {
            get {
                return ResourceManager.GetString("TextBooleanYes", resourceCulture);
            }
        }
    }
}
