<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>10.0.0-rc.0</Version>
    <Description>Utilitaires Kinetix pour ASP.NET Core.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="OpenTelemetry" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kinetix.Services\Kinetix.Services.csproj" />
  </ItemGroup>
</Project>
