//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinetix.Caching {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinetix.Caching.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Cache: Exception {1}.
        /// </summary>
        internal static string DebugException {
            get {
                return ResourceManager.GetString("DebugException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Cache: Could not create disk store. Initial cause was {1}.
        /// </summary>
        internal static string ErrorCouldNotCreateStore {
            get {
                return ResourceManager.GetString("ErrorCouldNotCreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Cache: Could not expire elements from disk due to {1}. Continuing....
        /// </summary>
        internal static string ErrorCouldNotExpireElements {
            get {
                return ResourceManager.GetString("ErrorCouldNotExpireElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Cache: Could not flush elements to disk due to {1}. Continuing....
        /// </summary>
        internal static string ErrorCouldNotFlushElements {
            get {
                return ResourceManager.GetString("ErrorCouldNotFlushElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Cache: Could not shut down disk cache. Initial cause was {1}.
        /// </summary>
        internal static string ErrorCouldNotShutdownStore {
            get {
                return ResourceManager.GetString("ErrorCouldNotShutdownStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} Cache is not alive..
        /// </summary>
        internal static string ExceptionCacheNotAlive {
            get {
                return ResourceManager.GetString("ExceptionCacheNotAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialise the {0} cache because its status is not UNINITIALISED..
        /// </summary>
        internal static string ExceptionCannotInitialise {
            get {
                return ResourceManager.GetString("ExceptionCannotInitialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create cache directory {0}..
        /// </summary>
        internal static string ExceptionCouldNotCreateDirectory {
            get {
                return ResourceManager.GetString("ExceptionCouldNotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file {0} could not created..
        /// </summary>
        internal static string ExceptionCouldNotCreateIndex {
            get {
                return ResourceManager.GetString("ExceptionCouldNotCreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store directory {0} exists and is not a directory..
        /// </summary>
        internal static string ExceptionStoreDirectoryIsFile {
            get {
                return ResourceManager.GetString("ExceptionStoreDirectoryIsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache: {0} has a maxElementsInMemory of 0. It is strongly recommended to have a maximumSize of at least 1. Performance is halved by not using a MemoryStore..
        /// </summary>
        internal static string WarnZeroMemoryStoreSize {
            get {
                return ResourceManager.GetString("WarnZeroMemoryStoreSize", resourceCulture);
            }
        }
    }
}
