//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinetixCore.ComponentModel {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinetixCore.ComponentModel.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la valeur doit être comprise entre {1} et {2}..
        /// </summary>
        internal static string ConstraintIntervalBornes {
            get {
                return ResourceManager.GetString("ConstraintIntervalBornes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au moins une borne doit être définie..
        /// </summary>
        internal static string ConstraintIntervalError {
            get {
                return ResourceManager.GetString("ConstraintIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} doit être renseigné.
        /// </summary>
        internal static string ConstraintNotNull {
            get {
                return ResourceManager.GetString("ConstraintNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date doit être comprise entre le 01/01/1753 et le 31/12/9999..
        /// </summary>
        internal static string DateContraintError {
            get {
                return ResourceManager.GetString("DateContraintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à l&apos;adresse mail doit être de la forme &apos;personne@exemple.com&apos;..
        /// </summary>
        internal static string ErrorConstraintEmail {
            get {
                return ResourceManager.GetString("ErrorConstraintEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la taille doit être inférieure à {0} caractères..
        /// </summary>
        internal static string ErrorConstraintStringLength {
            get {
                return ResourceManager.GetString("ErrorConstraintStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la taille doit être inférieure à {0} caractères et ne comporter aucun caractère spécial..
        /// </summary>
        internal static string ErrorConstraintStringLengthAlpha {
            get {
                return ResourceManager.GetString("ErrorConstraintStringLengthAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le booléen doit être une valeur &apos;True&apos; ou &apos;False&apos;..
        /// </summary>
        internal static string ErrorFormatBooleen {
            get {
                return ResourceManager.GetString("ErrorFormatBooleen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le code postal (ou code INSEE) doit être un nombre composé de 5 chiffres..
        /// </summary>
        internal static string ErrorFormatCodePostal {
            get {
                return ResourceManager.GetString("ErrorFormatCodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code trimestre doit être de la forme aaaaTt..
        /// </summary>
        internal static string ErrorFormatCodeTrimestre {
            get {
                return ResourceManager.GetString("ErrorFormatCodeTrimestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la date saisie doit être au format &apos;jj/mm/aaaa&apos;..
        /// </summary>
        internal static string ErrorFormatDate {
            get {
                return ResourceManager.GetString("ErrorFormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la date saisie est incorrecte..
        /// </summary>
        internal static string ErrorFormatDateValue {
            get {
                return ResourceManager.GetString("ErrorFormatDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n&apos;est pas une valeur valide pour un decimal..
        /// </summary>
        internal static string ErrorFormatDecimal {
            get {
                return ResourceManager.GetString("ErrorFormatDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} n&apos;est pas un entier..
        /// </summary>
        internal static string ErrorFormatEntier {
            get {
                return ResourceManager.GetString("ErrorFormatEntier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} n&apos;est pas un Guid valide..
        /// </summary>
        internal static string ErrorFormatGuid {
            get {
                return ResourceManager.GetString("ErrorFormatGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure doit être comprise entre 00:00 et 23:59.
        /// </summary>
        internal static string ErrorFormatHeure {
            get {
                return ResourceManager.GetString("ErrorFormatHeure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} n&apos;est pas un pourcentage valide..
        /// </summary>
        internal static string ErrorFormatPercentage {
            get {
                return ResourceManager.GetString("ErrorFormatPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le taux saisi doit être un décimal compris entre 0 et 100 avec deux chiffres après la virgule..
        /// </summary>
        internal static string ErrorFormatTaux {
            get {
                return ResourceManager.GetString("ErrorFormatTaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le numéro de téléphone doit comporter 10 chiffres..
        /// </summary>
        internal static string ErrorFormatTelephone {
            get {
                return ResourceManager.GetString("ErrorFormatTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la valeur doit être comprise entre {0} non compris et {1} compris.
        /// </summary>
        internal static string ErrorRangeDecimalLeftOpen {
            get {
                return ResourceManager.GetString("ErrorRangeDecimalLeftOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la valeur doit être comprise entre {0} non compris  et {1} non compris.
        /// </summary>
        internal static string ErrorRangeDecimalOpen {
            get {
                return ResourceManager.GetString("ErrorRangeDecimalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à la valeur doit être comprise entre {0} et {1} non compris.
        /// </summary>
        internal static string ErrorRangeDecimalRightOpen {
            get {
                return ResourceManager.GetString("ErrorRangeDecimalRightOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type ICustomTypeDescriptor not supported.
        /// </summary>
        internal static string ExceptionICustomTypeDescriptorNotSupported {
            get {
                return ResourceManager.GetString("ExceptionICustomTypeDescriptorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid value type {0}, {1} expected for property {2}..
        /// </summary>
        internal static string ExceptionInvalidValueType {
            get {
                return ResourceManager.GetString("ExceptionInvalidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not supported generic type : {0}..
        /// </summary>
        internal static string ExceptionNotSupportedGeneric {
            get {
                return ResourceManager.GetString("ExceptionNotSupportedGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type : {0}.
        /// </summary>
        internal static string ExceptionTypeDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type {0} non supporté pour la propriété &apos;{1}&apos;. Le type attendu est Int32..
        /// </summary>
        internal static string ExceptionTypeInt32Required {
            get {
                return ResourceManager.GetString("ExceptionTypeInt32Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La propriété {0} est en lecture seule, impossible de lui affecter une valeur..
        /// </summary>
        internal static string ReadOnlyProperty {
            get {
                return ResourceManager.GetString("ReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format invalide..
        /// </summary>
        internal static string SiretConstraintError {
            get {
                return ResourceManager.GetString("SiretConstraintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        internal static string TextBooleanNo {
            get {
                return ResourceManager.GetString("TextBooleanNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -.
        /// </summary>
        internal static string TextBooleanUndefined {
            get {
                return ResourceManager.GetString("TextBooleanUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        internal static string TextBooleanYes {
            get {
                return ResourceManager.GetString("TextBooleanYes", resourceCulture);
            }
        }
    }
}
