<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>10.0.1</Version>
    <Description>Implémentation ElasticSearch du module de recherche avancée Kinetix.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kinetix.Search.Core\Kinetix.Search.Core.csproj" />
  </ItemGroup>
</Project>
