<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>10.0.1</Version>
    <Description>Intégration à ASP.NET Core du module de reporting Kinetix.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kinetix.Reporting.Core\Kinetix.Reporting.Core.csproj" />
    <ProjectReference Include="..\Kinetix.Web\Kinetix.Web.csproj" />
  </ItemGroup>
</Project>
