<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>10.0.0</Version>
    <Description>Module pour intégrer EF Core dans les transactions Kinetix.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kinetix.Services\Kinetix.Services.csproj" />
  </ItemGroup>
</Project>
