<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>10.0.1</Version>
    <Description>Module de reporting Kinetix.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kinetix.Reporting.Annotations\Kinetix.Reporting.Annotations.csproj" />
    <ProjectReference Include="..\Kinetix.Services\Kinetix.Services.csproj" />
  </ItemGroup>
</Project>
